Update sparsebundlefs.cpp
Updating to fix errors
sparsebundlefs.cpp:171:56: error: 'pread' was not declared in this scope
sparsebundlefs.cpp:172:24: error: 'close' was not declared in this scope